name: Push image

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Push image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: 
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/workout:latest
          docker stop workout || true
          docker rm workout || true
          docker run -d -p 5000:80 --name workout ${{ secrets.DOCKERHUB_USERNAME }}/workout:latest
