name: Push image

on:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Push image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_KEY }}
        port: 49478
        script: |
          docker pull gnipka/workout:latest
          docker stop workout || true
          docker rm workout || true
          docker run -d -p 5000:80 --name workout gnipka/workout:latest
